server:
  port: 11221
spring:
  application:
    name: mongoTest
  data:
    mongodb:
      host: 192.168.1.191
      port: 27017
      database: store
      username: kellach
      password: kellach123
  http:
    multipart:
      max-file-size: 50Mb
      max-request-size: 50Mb
logging:
  level:
    root: info