server:
  port: 11221
  compression:
    enabled: true
    min-response-size: 1KB
    mime-types: application/json,application/xml,text/html,text/xml,text/plain
spring:
  application:
    name: mongoTest
  data:
    mongodb:
      host: 192.168.1.191
      port: 27017
      database: store
      username: kellach
      password: kellach123
  #数据源配置
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/risk_right?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&rewriteBatchedStatements=true&failOverReadOnly=false
    username: root
    password: kellach
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        prepStmtCacheSqlLimit: 2048
        useServerPrepStmts: true
        useLocalSessionState: true
        rewriteBatchedStatements: true
        cacheResultSetMetadata: true
        cacheServerConfiguration: true
        elideSetAutoCommits: true
        maintainTimeStats: false
logging:
  level:
    root: info
#mybatis plus 配置
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml #mapperxml 扫描目录
  global-config:
    db-config:
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      field-strategy: not_empty  #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
      id-type: auto     #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      db-type: mysql     #数据库类型
    banner: false   #关闭banner
    super-mapper-class: com.example.mongdb.mongdb.dao.BaseMapper   #定义基础mapper
  type-enums-package: com.example.mongdb.mongdb.cenum #枚举类 扫描路径
  type-aliases-package: com.example.mongdb.mongdb.entity   #model类 扫描路径