server:
  port: 8080
spring:
  application:
    name: mongoTest
  data:
    mongodb:
      host: 192.168.1.191
      port: 27017
      database: store
      username: kellach
      password: kellach123